pub mod emitter;
pub use emitter::X64Emitter;

pub mod ic;
pub use ic::{InlineCache, ICState};

// JIT compilation coordinator.
//
// Orchestrates Tier 1 and Tier 2 JIT compilation, manages compilation queues,
// and handles code cache management.

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::Mutex;

// ── Compiled Code ─────────────────────────────────────────────────────────────

/// Represents a block of native code generated by JIT compilation.
#[derive(Clone, Debug)]
pub struct CompiledCode {
    /// The tier this code was compiled at.
    pub tier: crate::vm::ExecutionTier,

    /// Native machine code bytes.
    pub code: Arc<Vec<u8>>,

    /// Address of the code in executable memory (placeholder for now).
    pub code_addr: usize,

    /// Entry point offset within the code.
    pub entry_offset: usize,

    /// Size of the code in bytes.
    pub code_size: usize,

    /// Deoptimization stubs for this code.
    pub deopt_stubs: HashMap<usize, DeoptStub>,

    /// When was this code compiled (in microseconds since epoch)?
    pub compile_time_us: u64,
}

impl CompiledCode {
    pub fn new(
        tier: crate::vm::ExecutionTier,
        code: Vec<u8>,
        entry_offset: usize,
        compile_time_us: u64,
    ) -> Self {
        let code_size = code.len();
        Self {
            tier,
            code: Arc::new(code),
            code_addr: 0, // Will be set when code is actually allocated
            entry_offset,
            code_size,
            deopt_stubs: HashMap::new(),
            compile_time_us,
        }
    }

    /// Get the entry point address.
    pub fn entry_point(&self) -> usize {
        self.code_addr + self.entry_offset
    }
}

// ── Deoptimization Stub ───────────────────────────────────────────────────────

/// A stub that handles deoptimization from JIT back to interpreter.
#[derive(Clone, Debug)]
pub struct DeoptStub {
    /// Offset within the compiled code where the deopt trap is.
    pub offset: usize,

    /// Bytecode PC corresponding to this deopt point.
    pub bytecode_pc: u32,

    /// Which values need to be recovered from registers/stack?
    pub live_values: Vec<LiveValue>,
}

#[derive(Clone, Debug)]
pub struct LiveValue {
    pub register_idx: u32,
    pub value_type: ValueType,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ValueType {
    Int64,
    Float64,
    Pointer,
    Unknown,
}

// ── JIT Coordinator ───────────────────────────────────────────────────────────

/// Central JIT compilation coordinator.
pub struct JitCoordinator {
    /// Compiled code cache, indexed by function ID.
    code_cache: Arc<Mutex<HashMap<u32, Arc<CompiledCode>>>>,

    /// Tier 1 compilation queue.
    tier1_queue: Arc<Mutex<Vec<u32>>>,

    /// Tier 2 compilation queue.
    tier2_queue: Arc<Mutex<Vec<u32>>>,

    /// Statistics.
    stats: Arc<Mutex<JitStats>>,
}

#[derive(Debug, Default)]
pub struct JitStats {
    pub tier1_compilations: u64,
    pub tier2_compilations: u64,
    pub deoptimizations: u64,
    pub total_compile_time_us: u64,
}

impl JitCoordinator {
    pub fn new() -> Self {
        Self {
            code_cache: Arc::new(Mutex::new(HashMap::new())),
            tier1_queue: Arc::new(Mutex::new(Vec::new())),
            tier2_queue: Arc::new(Mutex::new(Vec::new())),
            stats: Arc::new(Mutex::new(JitStats::default())),
        }
    }

    /// Compile IR to native code using the baseline JIT emitter.
    pub fn compile_baseline(&self, _func_id: u32) -> Arc<CompiledCode> {
        let mut emitter = X64Emitter::new();
        // Placeholder: Generate simple native code
        emitter.emit_mov_rax_imm64(42);
        emitter.emit_ret();

        let code = CompiledCode::new(
            crate::vm::ExecutionTier::BaselineJIT,
            emitter.code().to_vec(),
            0,
            0,
        );
        Arc::new(code)
    }

    // ── Code Cache Management ─────────────────────────────────────────────────

    /// Get compiled code for a function (if available).
    pub fn get_compiled_code(&self, func_id: u32, tier: crate::vm::ExecutionTier) -> Option<Arc<CompiledCode>> {
        self.code_cache
            .lock()
            .unwrap()
            .get(&func_id)
            .and_then(|code| {
                if code.tier == tier || (code.tier as u8) > (tier as u8) {
                    Some(code.clone())
                } else {
                    None
                }
            })
    }

    /// Store compiled code in the cache.
    pub fn cache_code(&self, func_id: u32, code: Arc<CompiledCode>) {
        // Update stats before moving code
        let mut stats = self.stats.lock().unwrap();
        match code.tier {
            crate::vm::ExecutionTier::BaselineJIT => stats.tier1_compilations += 1,
            crate::vm::ExecutionTier::OptimizingJIT => stats.tier2_compilations += 1,
            _ => {}
        }
        stats.total_compile_time_us += 1000; // Placeholder
        drop(stats); // Release lock before inserting

        self.code_cache.lock().unwrap().insert(func_id, code);
    }

    // ── Compilation Queue Management ──────────────────────────────────────────

    /// Enqueue a function for Tier 1 compilation.
    pub fn enqueue_tier1(&self, func_id: u32) {
        println!("Enqueuing func_id {} for Tier 1 compilation", func_id);
        self.tier1_queue.lock().unwrap().push(func_id);
    }

    /// Enqueue a function for Tier 2 compilation.
    pub fn enqueue_tier2(&self, func_id: u32) {
        self.tier2_queue.lock().unwrap().push(func_id);
    }

    /// Dequeue the next function to compile in Tier 1.
    pub fn dequeue_tier1(&self) -> Option<u32> {
        self.tier1_queue.lock().unwrap().pop()
    }

    /// Dequeue the next function to compile in Tier 2.
    pub fn dequeue_tier2(&self) -> Option<u32> {
        self.tier2_queue.lock().unwrap().pop()
    }

    /// Get current size of Tier 1 queue.
    pub fn tier1_queue_size(&self) -> usize {
        self.tier1_queue.lock().unwrap().len()
    }

    /// Get current size of Tier 2 queue.
    pub fn tier2_queue_size(&self) -> usize {
        self.tier2_queue.lock().unwrap().len()
    }

    // ── Statistics ────────────────────────────────────────────────────────────

    /// Get JIT statistics.
    pub fn stats(&self) -> JitStats {
        self.stats.lock().unwrap().clone()
    }

    /// Record a deoptimization.
    pub fn record_deoptimization(&self) {
        self.stats.lock().unwrap().deoptimizations += 1;
    }
}

impl Clone for JitStats {
    fn clone(&self) -> Self {
        Self {
            tier1_compilations: self.tier1_compilations,
            tier2_compilations: self.tier2_compilations,
            deoptimizations: self.deoptimizations,
            total_compile_time_us: self.total_compile_time_us,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_code_cache() {
        let coordinator = JitCoordinator::new();

        let code = CompiledCode::new(
            crate::vm::ExecutionTier::BaselineJIT,
            vec![0x90, 0xc3], // NOP, RET
            0,
            0,
        );
        let code_arc = Arc::new(code);

        coordinator.cache_code(42, code_arc.clone());

        let retrieved = coordinator.get_compiled_code(42, crate::vm::ExecutionTier::BaselineJIT);
        assert!(retrieved.is_some());

        let stats = coordinator.stats();
        assert_eq!(stats.tier1_compilations, 1);
    }

    #[test]
    fn test_compilation_queues() {
        let coordinator = JitCoordinator::new();

        coordinator.enqueue_tier1(1);
        coordinator.enqueue_tier1(2);
        coordinator.enqueue_tier2(3);

        assert_eq!(coordinator.tier1_queue_size(), 2);
        assert_eq!(coordinator.tier2_queue_size(), 1);

        assert_eq!(coordinator.dequeue_tier1(), Some(2)); // LIFO
        assert_eq!(coordinator.dequeue_tier2(), Some(3));
    }
}
