/// Generate a C header file exposing the ember runtime API.
/// This allows a self-hosted Nimble compiler to call runtime functions.
pub fn generate_runtime_header() -> String {
    let mut header = String::new();
    header.push_str("// Nimble Runtime API\n");
    header.push_str("// Generated by the Nimble compiler for self-hosting support\n\n");
    header.push_str("#ifndef NIMBLE_RUNTIME_H\n");
    header.push_str("#define NIMBLE_RUNTIME_H\n\n");
    header.push_str("#include <stdint.h>\n\n");

    // Memory
    header.push_str("void* nimble_alloc(uint64_t size);\n");
    header.push_str("void nimble_free(void* ptr, uint64_t size);\n");
    header.push_str("void* nimble_realloc(void* ptr, uint64_t old_size, uint64_t new_size);\n\n");

    // Print
    header.push_str("void nimble_print(const char* str);\n");
    header.push_str("void nimble_print_str(const char* str);\n");
    header.push_str("void nimble_print_i64(int64_t val);\n");
    header.push_str("void nimble_print_f64(double val);\n\n");

    // String
    header.push_str("typedef struct { char* data; int64_t length; } NimbleString;\n");
    header.push_str("NimbleString nimble_string_new(const char* raw, int64_t len);\n");
    header.push_str("void nimble_string_free(NimbleString s);\n\n");

    // Panic
    header.push_str("void nimble_panic(const char* msg);\n\n");

    header.push_str("#endif // NIMBLE_RUNTIME_H\n");
    header
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_contains_guard() {
        let header = generate_runtime_header();
        assert!(header.contains("NIMBLE_RUNTIME_H"));
    }

    #[test]
    fn header_contains_alloc() {
        let header = generate_runtime_header();
        assert!(header.contains("nimble_alloc"));
    }

    #[test]
    fn header_contains_print() {
        let header = generate_runtime_header();
        assert!(header.contains("nimble_print_i64"));
    }
}
